services:
    # redis:
    #     image: redis:alpine
    #     command: [ redis-server, --maxmemory 128mb, --maxmemory-policy volatile-lru, --save "" ]

    # ?

    php:
        #user: '501:501' # set to your uid:gid
        image: gcr.io/it-department-150323/pimcore/php
        environment:
            COMPOSER_HOME: /var/www/html
            server_version: 8.0.26
            driver: pdo_mysql
            # PHP_IDE_CONFIG: serverName=localhost
            # # Feed installer configuration via ENV variables.
            # # See: https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Advanced_Installation_Topics.html#page_Advanced-Installation-Topics
            DB_USER: 
            DB_PASSWORD: 
            DB_HOST: 
            DB_NAME: pimcore
        # depends_on:
        #     db:
        #         condition: service_healthy
        volumes:
            - .:/var/www/html
            - ./config/local/database.yml:/config/local/database.yml
        ports:
            - 8080:8080

