[supervisord]
pidfile=/tmp/supervisord.pid  ; (supervisord pidfile;default supervisord.pid)
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root

[include]
files = /etc/supervisor/conf.d/*.conf

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:messenger-consume-search-backend]
user=www-data
command=php /var/www/html/bin/console messenger:consume pimcore_search_backend_message --memory-limit=250M --time-limit=3600
numprocs=1 # Increase if queue is getting backed up
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:messenger-consume-maintenance]
user=www-data
command=php /var/www/html/bin/console messenger:consume pimcore_maintenance --memory-limit=250M --time-limit=3600
numprocs=1
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:messenger-consume-others]
user=www-data
command=php /var/www/html/bin/console messenger:consume pimcore_core pimcore_scheduled_tasks pimcore_image_optimize pimcore_asset_update --memory-limit=250M --time-limit=3600
numprocs=1
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:maintenance]
user=www-data
command=bash -c 'php /var/www/html/bin/console pimcore:maintenance && sleep 3600'
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:messenger-consume-data-import]
user=www-data
command=php /var/www/html/bin/console messenger:consume pimcore_data_import --memory-limit=128M --time-limit=360 --limit=128
numprocs=1 # To increase worker count for parallel processes, update the following in the config.yaml: pimcore_data_importer.messenger_queue_processing.worker_count_parallel
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
